// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldyzpnmymigylwlvpxns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkeXpwbm15bWlneWx3bHZweG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTU5MDMsImV4cCI6MjA1ODQ5MTkwM30.aEqHRrSMrot0rMBU-BG811wP4rhE8_Ty5iC_szgL6Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);